# Generated by Django 2.2.1 on 2019-06-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_institutionalemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionalemail',
            name='address_email',
        ),
    ]
