# Generated by Django 2.2.1 on 2019-06-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_institutionalemail_address_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionalemail',
            name='body_email',
        ),
    ]
