# Generated by Django 2.2.1 on 2019-06-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_institutionalemail_body_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalemail',
            name='address_email',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutionalemail',
            name='body_email',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
