# Generated by Django 2.2.1 on 2019-06-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_institutionalemail_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalemail',
            name='address_email',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutionalemail',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
            preserve_default=False,
        ),
    ]
