# Generated by Django 2.2.1 on 2019-06-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_institutionalemail_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalemail',
            name='address_email',
            field=models.CharField(max_length=50),
        ),
    ]
