# Generated by Django 2.2.1 on 2019-06-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20190629_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalemail',
            name='title_email',
            field=models.CharField(default='Assunto do email', editable=False, max_length=20),
        ),
    ]
